### ISSUE TITLE
IntelliJ IDEA上とPrism Launcher（Fabric 1.20）で動作確認したところ、テクスチャの設定ができなくなっているようです。

### ISSUE THREAD

**Issue by a9uabit** [Yokohama-Miyazawa/MaidIllagerFabric#5]
IntelliJ IDEA上とPrism Launcher（Fabric 1.20）で動作確認したところ、テクスチャの設定ができなくなっているようです。
「外観設定」をクリックしても設定画面に進めません。
確認をお願いします。

_Originally posted by @Yokohama-Miyazawa in https://github.com/UECYukkuriProject/MaidIllagerFabric/issues/4#issuecomment-1891803716_

**Comment by a9uabit** [comment]
@Yokohama-Miyazawa  承知しました。少々お待ちください

**Comment by a9uabit** [comment]
> IntelliJ IDEA上とPrism Launcher（Fabric 1.20）で動作確認したところ、テクスチャの設定ができなくなっているようです。 「外観設定」をクリックしても設定画面に進めません。 確認をお願いします。

ただいま、確認・特定しました。修正しますのでもうしばらくお待ち下さい

**Comment by a9uabit** [comment]
修正しました。

**Comment by Yokohama-Miyazawa** [comment]
正常に動作することを確認しました。
ありがとうございます。
